import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SearchAutocomplete from "@/components/Search/SearchAutoComplete";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food Fetching App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("main layout")
  return (
    <html lang="en">
      <body className={`${inter.className} p-20`}>
        <header className="">
        <Navbar />
        <Suspense>
        <SearchAutocomplete />
        </Suspense>
        </header>
        {children}
      </body>
    </html>
  );
}
